version: '2'
services:
  csgo-steamcmd:
    build: .
    working_dir: /var/app
    command: ["+login anonymous", "+force_install_dir /var/app/server", "+app_update 740 validate", "quit"]
    ports:
     - "27015:27015"
     - "27015:27015/udp"
     - "27020:27020/udp"
     - "26900:26900/udp"
    volumes:
     - f:/test:/var/app/server
    networks:
      - default
      - csgonet
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
networks:
  csgonet:
    external: true