version: '2'
services:
  csgo-steamcmd:
    build: .
    working_dir: /var/app
    command: ["+login anonymous", "+force_install_dir /var/app/server", "+app_update 740 validate", "+quit"]
    volumes:
     - f:/mnt/nbd0:/var/app/server
    networks:
      - default
      - csgonet
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
networks:
  csgonet:
    external: true