version: '2'
services:
  csgo-srcds:
    build: .
    working_dir: /var/app
    command: ["/var/app/server/srcds_run", "-game csgo", "-console", "-usercon", "+game_type 0", "+game_mode 1", "+map de_dust2", "+ip 0.0.0.0"]
    ports:
     - "27015:27015"
     - "27015:27015/udp"
     - "27020:27020/udp"
     - "26900:26900/udp"
    volumes:
     - f:/mnt/nbd0:/var/app/server
    networks:
      - default
      - csgonet
    logging:
      driver: redis-log-driver
      options:
        redis-address: redis-csgonet:6379
networks:
  csgonet:
    external: true