version: '2'
services:
  csgo-rcon:
    environment:
      NODE_ENV: development-local
      PORT: 8000
    build: .
    working_dir: /var/app
    command: /node_modules/.bin/nodemon --inspect=9231
    ports:
     - "8000:8000"
    volumes:
     - .:/var/app
    depends_on:
      - "csgo-db"
    networks:
      - default
      - csgonet


networks:
  csgonet:
    external: true