version: '2'
services:
  csgo-servers-worker:
    environment:
      NODE_ENV: development-local
      MONGDB_DEBUG: "true"
      MONGODB_CONNECTION_STRING: "mongodb://mongodb-csgonet:27017/service-servers"
      NATS_CONNECTION_URI: "nats://nats-csgonet:4222"
    build: .
    working_dir: /var/app
    command: node server.js
    ports:
     - "21:21"
     - "40110-40210:40110-40210"
     - "27015:27015"
     - "27015:27015/udp"
     - "27020:27020/udp"
     - "26900:26900/udp"
    volumes:
     - f:/images:/var/images
    networks:
      - default
      - csgonet
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
networks:
  csgonet:
    external: true