version: '2'
services:
  csgo-images:
    environment:
      NODE_ENV: development-local
      PORT: 8002
      MONGDB_DEBUG: "true"
      MONGODB_CONNECTION_STRING: "mongodb://mongodb-csgonet:27017/service-images"
      NATS_CONNECTION_URI: "nats://nats-csgonet:4222"
    build: .
    working_dir: /var/app
    command: node server.js
    ports:
     - "8002:8002"
    networks:
      - default
      - csgonet
    privileged: true
    cap_add:
      - ALL

networks:
  csgonet:
    external: true